version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
  
  airflow-init:
    image: apache/airflow:2.10.5
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_SKIP_GROUP_CHECK=true
    depends_on:
      - postgres
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-webserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_SKIP_GROUP_CHECK=true
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW__API__ENABLE_EXPERIMENTAL_API=True
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__WEBSERVER__AUTHENTICATE=True
      - AIRFLOW__WEBSERVER__WEB_SERVER_ALLOW_WEB_API=True
      
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - airflow_plugins:/opt/airflow/plugins
      - ./talend/jobs:/opt/airflow/talend_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    user: "root"
    depends_on:
      - postgres
      - airflow-init
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_SKIP_GROUP_CHECK=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - ./talend/jobs:/opt/airflow/talend_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    user: "root"
    depends_on:
      - postgres
      - airflow-init
    command: ["scheduler"]

  talend-jobs:
    image: openjdk:11
    container_name: talend-jobs
    restart: always
    volumes:
      - ./talend/jobs:/jobs
    working_dir: /jobs
    command: ["tail", "-f", "/dev/null"]

  mer_app:
    build: .
    container_name: mer_app
    user: "root"
    environment:
      - MONGODB_URI=mongodb+srv://salouaouissa:jD5IDdTVLoITMCpL@cluster0.nwqo9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "5000:5000"
      - "8081:8081"
    volumes:
      - ./scripts:/scripts:ro
      - ./PFE:/app/mern/PFE
      - mer_app_node_modules:/app/mern/PFE/node_modules
      - frontend_node_modules:/app/mern/PFE/Frontend/node_modules
    working_dir: /app/mern/PFE
    command: bash -c "npm install && cd Frontend && npm install -D esbuild@0.25.0 && cd .. && (node Backend/Server.js & cd Frontend && npm run dev -- --host 0.0.0.0 --port 8081)"
    depends_on:
      - postgres
      - airflow-webserver

volumes:
  mer_app_node_modules:
  frontend_node_modules:  
  postgres_data:
  airflow_data:
  airflow_plugins: