version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:latest
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - postgres
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db init
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - airflow_plugins:/opt/airflow/plugins
      - ./talend/jobs:/opt/airflow/talend_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    user: "airflow"
    depends_on:
      - postgres
      - airflow-init
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
      - ./talend/jobs:/opt/airflow/talend_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - airflow-init
    command: ["scheduler"]

  pentaho:
    image: zhicwu/pdi-ce:latest
    container_name: pentaho
    restart: always
    ports:
      - "8085:8083"
    volumes:
      - ./pentaho:/opt/pentaho
    command: ["tail", "-f", "/dev/null"]

  talend-jobs:
    image: openjdk:11
    container_name: talend-jobs
    restart: always
    volumes:
      - ./talend/jobs:/jobs
    working_dir: /jobs
    command: ["tail", "-f", "/dev/null"]

  mer_app:
    build: .
    container_name: mer_app
    environment:
      - MONGODB_URI=mongodb+srv://salouaouissa:jD5IDdTVLoITMCpL@cluster0.nwqo9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/scripts:ro
      - ./PFE:/app/mern/PFE
    working_dir: /app/mern/PFE
    command: bash -c "npm install && npm start"
    depends_on:
      - postgres
      - airflow-webserver
  frontend:
    image: node:20-slim
    container_name: frontend
    volumes:
      - ./PFE/Frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "8081:8081"  # Redirige le port 8081 de l'hôte vers le port 8081 du conteneur
    environment:
      - VITE_API_URL=http://mer_app:5000
    command: >
      bash -c "npm install &&
              npm run dev -- --host 0.0.0.0 --port 8081"
    depends_on:
      - mer_app
# Ajouter cette section à vos volumes définis
volumes:
  frontend_node_modules: 
  mongodb_data:
  postgres_data:
  airflow_data:
  airflow_plugins: